import type { ExploreSettings, ComposerSettings } from './preset';

export type SnapshotSource = 'explore' | 'cymatics' | 'composer';

export interface Snapshot {
  id: string;
  /** Display name — auto-generated by default, user can rename */
  name: string;
  /** Which screen the snapshot was taken on */
  source: SnapshotSource;
  /** Full parameter state at capture time */
  settings: ExploreSettings | ComposerSettings;
  /** Unix timestamp */
  createdAt: number;
}
